spring.application.name=kitchenstaff-api

server.port=8080

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/kitchenstaff_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT configuration
app.jwt.secret=KitchenstaffSecretKeyForJwtTokenGeneration2026KitchenstaffSecretKey
app.jwt.expiration-ms=86400000

# API
app.api.version=v1